on:
  push: 
    branches:
      - main
  workflow_dispatch: 
      
jobs: 
  download:
    name: Download
    runs-on: self-hosted
    steps:
      - run: bash ~/actions-runner/vostok-ugolok-api/download.sh
  start:
    needs: download
    runs-on: self-hosted
    name: Start server
    steps:
      - run: bash ~/actions-runner/vostok-ugolok-api/startup.sh
     
  #containerize:
  #  needs: download
  #  name: Build a docker container
  #  runs-on: self-hosted
  #  steps:
  #   - run: bash ~/github-ci/containerize.sh
