on:
  push: 
    branches:
      - main
  workflow_dispatch: 
      
jobs: 
  download:
    name: Download
    runs-on: self-hosted
    steps:
      - run: bash ~/github-ci/download.sh
  #containerize:
  #  needs: download
  #  name: Build a docker container
  #  runs-on: self-hosted
  #  steps:
  #   - run: bash ~/github-ci/containerize.sh
