on:
  push: 
    branches:
      - main
  workflow_dispatch: 
      
jobs: 
  download:
    name: Select files from dist folder
    runs-on: self-hosted
    steps:
      - run: bash ~/github-ci/download.sh
  containerize:
    needs: download
    name: Build a docker container
    runs-on: self-hosted
    env:
      working-directory: ~/vostok-ugolok-api
    steps:
     - run: npm i
     #- run: tsc
     - run: docker stop vostok-ugolok-api
     - run: docker rm vostok-ugolok-api
     - run: docker rmi vostok-ugolok-api
     - run: docker build -t vostok-ugolok-api .
     - run: docker run -d --name vostok-ugolok-api -p 47474:4999 vostok-ugolok-api
