on:
  push: 
    branches:
      - main
  workflow_dispatch: 
      
jobs: 
  download:
    name: Select files from dist folder
    runs-on: self-hosted
    steps:
      - run: bash ~/github-ci/download.sh
  containerize:
    name: Build a docker container
    runs-on: self-hosted
    steps:
     - run: bash ~/github-ci/containerize.sh
